package com.mycompany.profinfin;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class interfazCierreCaja extends javax.swing.JFrame {
    
    public interfazCierreCaja() {
        initComponents();
        cargarInventario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollClientes = new javax.swing.JScrollPane();
        tablaCierre = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();
        Refrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación Tienda Nordic Style");
        setBackground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(200, 200));

        tablaCierre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Total Compra"
            }
        ));
        tablaCierre.setColumnSelectionAllowed(true);
        tablaCierre.getTableHeader().setReorderingAllowed(false);
        scrollClientes.setViewportView(tablaCierre);
        tablaCierre.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Titulo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Menú de Cierre de caja");

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salir2.png"))); // NOI18N
        eliminar1.setText("Salir");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });

        Refrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh.png"))); // NOI18N
        Refrescar.setText("Actualizar");
        Refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Refrescar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(Titulo)))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refrescar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        
    }//GEN-LAST:event_agregarActionPerformed
    
    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void RefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarActionPerformed
        clearInventario();
        cargarInventario();
    }//GEN-LAST:event_RefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void cargarInventario(){
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Cantidad", "Precio unitario"}, ProFinfin.inv.size());
        tablaCierre.setModel(modelo);
        
        TableModel modeloDatos= tablaCierre.getModel();
        for (int i = 0; i < ProFinfin.inv.size(); i++) {
            Articulos articulo1=ProFinfin.inv.get(i);
            modeloDatos.setValueAt(articulo1.getPosicion(), i, 0);
            modeloDatos.setValueAt(articulo1.getInvNombre(), i, 1);
            modeloDatos.setValueAt(articulo1.getCantDisp(), i, 2);
            modeloDatos.setValueAt(articulo1.getPrecio(), i, 3);
        }
    }
    public void clearInventario(){
       tablaCierre.removeAll();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refrescar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JTable tablaCierre;
    // End of variables declaration//GEN-END:variables

    
}
